---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен быть адаптивным в русской и английской версиях
  - На сайте должен быть реализован функционал ввода имени и контактных данных пользователя при заказе.
  - Пользователь должен иметь возможность просматривать свои заказы. 
  - Корзина должна очищаться после оформления заказа.
  - Должна быть нумерация страниц с товарами.
  - Описание товара в карточке товара должно соответсвовать выбранному языку сайта.
  - После выбора категрии товара должна быть возможность вернуться к просмотру всех категорий.
  - Должна отображаться иконка английского языка при выборе английского языка сайта.
  - Кнопка добавления товара в корзину не должна выходить за пределы карточки товара.
  - Кнопка добавления товара в корзину должна иметь одинаковые отступы внутри карточки товара.
  - Фото товара в карточке товара должно иметь нормальное разрешение.
  - При указывании диапазона цен, должны быть показаны товары с ценами включительно.
  - Пользователь должен иметь возможность просматривать дополнительные фото товара в карточке товара.
  - Название товара, фото товара и описание товара должны совпадать.
  - Название товара, категории, производителя должно начинаться с большой буквы или цифры.
  - В козине должно быть выравнивание в один столбец цифр, обозначающих количество заказываемого товара.
  - При нажатии пользователем кнопки Оформить заказ, заказ должен отправляться на сервер.
  - В сплывающем окне успешно оформленного заказа кнопка в виде крестика должна закрывать окно.
  - При изменении разрешения устройства текст не должен выходить за пределы блоков.
  - После перезагрузки страницы должен сохраняться выбранный язык сайта.
  - При переходе в карточку товара после фильтрации товаров по ключевому слову, категории или производителю и возврате обратно к списку товаров фильтр должен сохраняться.
